### ISSUE TITLE
RDS IAM Database Authentication

### ISSUE THREAD

**Issue by md5** [aws/aws-sdk-rails#80]
Are there any plans for this gem to support [RDS IAM Database Authentication](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.html)?

**Comment by mullermp** [comment]
Thanks for opening up an issue. We didn't have specific plans to add this (mainly because we weren't aware of this feature). I'm happy to make this as a feature request and contributions are always welcome. What did you have in mind for supporting this feature? The Ruby SDK does have an abstraction for this - https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/RDS/AuthTokenGenerator.html

**Comment by md5** [comment]
@mullermp I think since the tokens have a lifetime of 15 minutes, any implementation would need to be aware of that and would need to regenerate the token for new connections in the connection pool if the token has expired (or on a reconnect). The ActiveRecord internals for this don't seem particularly well-documented from what I could see, but I think it would probably need a wrapper adapter that knows about these details and delegates to the standard ActiveRecord adapter.

So in terms of a developer interface, I could imagine something like this:

```yaml
default: &default
  adapter: aws-rds-iam
  delegate_adapter: postgresql
  encoding: unicode
  sslmode: require
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
  <<: *default
  username: some_user
```

The `aws-rds-iam` adapter would supply the generated token to the PostgreSQL adapter in this case as the normal `password` setting.
